---
title: "pw023_cellarea"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(readxl)
library(dplyr)
library(ggplot2)

knitr::opts_knit$set(root.dir = '/Users/dylanschaff/Library/CloudStorage/GoogleDrive-dyschaff@sydshafferlab.com/My Drive/White_Shared/cloud/experiment_ids/pw023')

colors <- c('500' = '#21618C',
            '1000' = '#95A5A6',
            '5000' = '#B03A2E')

colors_il6st <- c('Low' = '#55C0EE',
                  'High' = '#EF3E69')

#dir.create('cellarea_count')
```

## Import cell area csvs
```{r}
setwd('cellarea_outputs')
  area_files <- list.files(pattern = '*.csv', recursive=T, full.names = T)
  areas <- lapply(area_files, read.csv, header = T)
names(areas) <- area_files

areas <- lapply(areas, function(x) {x$fraction <- x$Cell_area/x$Cell_area[x$Condition == "Blank"];return(x)})
areas <- lapply(areas, function(x) x[x$Condition != "Blank", ])
areas <- lapply(areas, function(x) {x$X <- NULL;return(x)})


```
## Convert to data frames
```{r}

# Get all experimental wells together
areas_df <- bind_rows(areas, .id= 'column_label')

areas_exp <- areas_df[grepl('IL6ST', areas_df$Condition), ]

area_df <- data.frame(area = areas_exp$Cell_area,
                      frac = areas_exp$fraction,
                      il6st = sapply(areas_exp$Condition, function(x) strsplit(x,'_')[[1]][[7]]),
                      seeding_num = sapply(areas_exp$Condition, function(x) strsplit(x,'_')[[1]][[8]]),
                      plate = sapply(areas_exp$Condition, function(x) strsplit(x,'_')[[1]][[9]]))
area_df <- data.frame(lapply(area_df, function(x) {gsub("K", "000", x)}))
area_df$area <- as.numeric(area_df$area)
area_df$frac <- as.numeric(area_df$frac)


# Organize control wells
areas_control <- areas_df[grepl('Control', areas_df$Condition), ]

process_data <- function(data, plate_filter, well_filter, il6st_value, plate_value) {
  filtered_data <- data[grepl(plate_filter, data$Condition) & grepl(well_filter, data$Condition), ]
  filtered_data$il6st <- il6st_value
  filtered_data$seeding_num <- sapply(filtered_data$Condition, function(x) strsplit(x, '_')[[1]][[8]])
  filtered_data$plate <- plate_value
  filtered_data <- data.frame(lapply(filtered_data, function(x) gsub("K", "000", x)))
  return(filtered_data)
}

areas_ctrl_for_lowplate5 <- process_data(areas_control, 'Plate2', '', 'Low', 'Plate5')
areas_ctrl_for_allhigh <- process_data(areas_control, 'Plate1', 'Well[4-6]', 'High', 'Plate1')
areas_ctrl_for_alllow <- process_data(areas_control, 'Plate1', 'Well[1-3]', 'Low', 'Plate1')

areas_ctrl <- rbind(areas_ctrl_for_alllow, areas_ctrl_for_lowplate5, areas_ctrl_for_allhigh)

area_ctrl_df <- data.frame(area = as.numeric(areas_ctrl$Cell_area),
                           frac = as.numeric(areas_ctrl$fraction),
                           il6st = areas_ctrl$il6st,
                           seeding_num = areas_ctrl$seeding_num,
                           plate = areas_ctrl$plate)

```

# Add mean area and mean fraction
```{r}

area_df$mean_area <- ave(area_df$area, 
                           area_df$il6st, 
                           area_df$seeding_num, 
                           FUN = mean)

area_df$mean_frac <- ave(area_df$frac, 
                           area_df$il6st, 
                           area_df$seeding_num, 
                           FUN = mean)

area_df <- area_df[order(area_df$il6st, as.numeric(area_df$seeding_num), area_df$plate), ]

#dir.create('cellarea_count/rdata')
save(area_df, file='cellarea_count/rdata/areas_exp.RData')

area_ctrl_df$mean_area <- ave(area_ctrl_df$area, 
                           area_ctrl_df$il6st, 
                           area_ctrl_df$seeding_num,
                           area_ctrl_df$plate,
                           FUN = mean)

area_ctrl_df$mean_frac <- ave(area_ctrl_df$frac, 
                           area_ctrl_df$il6st, 
                           area_ctrl_df$seeding_num,
                           area_ctrl_df$plate, 
                           FUN = mean)

area_ctrl_df <- area_ctrl_df[order(area_ctrl_df$il6st, as.numeric(area_ctrl_df$seeding_num), area_ctrl_df$plate), ]
save(area_ctrl_df, file='cellarea_count/rdata/areas_ctrl.RData')

```

## reload
```{r}
load('cellarea_count/rdata/areas_exp.RData')
load('cellarea_count/rdata/areas_ctrl.RData')

```

## Raw area plots
```{r}
#dir.create('cellarea_count/plots')

# Raw counts
pdf(file="cellarea_count/plots/raw_plots.pdf")
seeding_nums <- list()
for(i in unique(area_df$seeding_num)) {
  t <- filter_all(area_df, any_vars(.==i))
  t$il6st <- factor(t$il6st, levels = c("Low", "High"))
  print(ggplot(t) +
          geom_violin(aes(x= il6st, y= area, fill = seeding_num)) +
          geom_point(aes(x= il6st, y= area), color = 'black') +
          labs(x="il6st level", y="cell area", title="cell area") + 
          scale_color_manual(values = colors[i]) + 
          scale_fill_manual(values = colors[i]))
  print(ggplot(t, aes(x= il6st, y= area, fill = seeding_num)) +
          geom_boxplot() +
          labs(x="il6st level", y="cell area", title="cell area") + 
          scale_fill_manual(values = colors[i]))
  seeding_nums[[i]] <- t
}
dev.off()

```
## Normalized areas
```{r}
# Write scaling factor
scaling_factor_alllow <- area_ctrl_df[4,6]/area_ctrl_df[4,6]
scaling_factor_lowplate5 <- area_ctrl_df[7,6]/area_ctrl_df[4,6]
scaling_factor_allhigh <- area_ctrl_df[1,6]/area_ctrl_df[4,6]

# Add scaling factor column
add_norms <- list()
for(i in unique(area_df$il6st)) {
  t <- filter_all(area_df, any_vars(.==i))
  
  if(i == 'High'){
    t$sf <- c(rep(scaling_factor_allhigh, nrow(t)))
    
  } else {
    for(j in unique(t$plate)){
      s <- filter_all(area_df, any_vars(.==j))
      
      if(j == 'Plate5'){
        t$sf[t$plate == j] <- c(rep(scaling_factor_lowplate5, 6))
        
      } else {
        t$sf[t$plate == j] <- c(rep(scaling_factor_alllow, 3))
        
      }}}
  add_norms[[i]] <- t
}
area_df <- bind_rows(add_norms, .id= 'column_label')

# Add normalized area column
area_df$norm_area <- area_df$area/area_df$sf
area_df$norm_mean_area <- area_df$mean_area/area_df$sf


area_df <- area_df[order(rev(area_df$il6st), as.numeric(area_df$seeding_num), area_df$plate), ]
area_ctrl_df <- area_ctrl_df[order(rev(area_ctrl_df$il6st), as.numeric(area_ctrl_df$seeding_num), area_ctrl_df$plate), ]

save(area_df, file='cellarea_count/rdata/areas_exp.RData')
save(area_ctrl_df, file='cellarea_count/rdata/areas_ctrl.RData')
```

## LOAD
```{r}
load('cellarea_count/rdata/areas_exp.RData')
load('cellarea_count/rdata/areas_ctrl.RData')
load('cellarea_count/rdata/pvals.RData')

```

## Normalized area plots
```{r}

# Norm counts
pdf(file="cellarea_count/plots/norm_plots.pdf")
seeding_nums_norm <- list()
for(i in unique(area_df$seeding_num)) {
  t <- filter_all(area_df, any_vars(.==i))
  t$il6st <- factor(t$il6st, levels = c("Low", "High"))
  print(ggplot(t) +
          geom_violin(aes(x= il6st, y= norm_area, fill = seeding_num)) +
          geom_point(aes(x= il6st, y= norm_area), color = 'black') +
          labs(x="il6st level", y="norm cell area", title="norm cell area") + 
          scale_fill_manual(values = colors[i]))
  print(ggplot(t, aes(x= il6st, y= norm_area, fill = seeding_num)) +
          geom_boxplot() +
          labs(x="il6st level", y="norm cell area", title="norm cell area") + 
          scale_fill_manual(values = colors[i]))
  seeding_nums_norm[[i]] <- t
}
dev.off()

```

## Log2 area plots
```{r}
#dir.create('cellarea_count/plots')

# Log2 FC
pdf(file="cellarea_count/plots/log2_plots.pdf")
for(i in unique(area_df$seeding_num)) {
  t <- filter_all(area_df, any_vars(.==i))
  t$il6st <- factor(t$il6st, levels = c("Low", "High"))
  print(ggplot(t) +
          geom_violin(aes(x= il6st, y= log2(norm_area), fill = seeding_num)) +
          geom_point(aes(x= il6st, y= log2(norm_area)), color = 'black') +
          labs(x="il6st level", y="log2(norm cell area)", title="log2(norm cell area)") + 
          scale_fill_manual(values = colors[i]))
  print(ggplot(t, aes(x= il6st, y= log2(norm_area), fill = seeding_num)) +
          geom_boxplot() +
          labs(x="il6st level", y="log2(norm cell area)", title="log2(norm cell area)") + 
          scale_fill_manual(values = colors[i]))
}
dev.off()


```

## pval (?)
```{r}

pval_5000 <- t.test(area_df$norm_area[area_df$seeding_num == '5000' & area_df$il6st == 'High'],
                    area_df$norm_area[area_df$seeding_num == '5000' & area_df$il6st == 'Low'],
                    alternative = 'greater')$p.value

pval_1000 <- t.test(area_df$norm_area[area_df$seeding_num == '1000' & area_df$il6st == 'High'],
                    area_df$norm_area[area_df$seeding_num == '1000' & area_df$il6st == 'Low'],
                    alternative = 'greater')$p.value

pval_500 <- t.test(area_df$norm_area[area_df$seeding_num == '500' & area_df$il6st == 'High'],
                   area_df$norm_area[area_df$seeding_num == '500' & area_df$il6st == 'Low'],
                   alternative = 'greater')$p.value

pvals_df <- data.frame(pval = c(pval_500, pval_1000, pval_5000),
                       seeding_num = c(500, 1000, 5000))

save(pvals_df, file='cellarea_count/rdata/pvals.RData')

```

## LOG2FC w pval per density
```{r}

# Log2 FC w pval
pdf(file="cellarea_count/plots/log2_pval_norm_plots.pdf")
for(i in unique(area_df$seeding_num)) {
  t <- filter_all(area_df, any_vars(.==i))
  t$il6st <- factor(t$il6st, levels = c("Low", "High"))
  p <- filter_all(pvals_df, any_vars(.==i))
  print(ggplot(t) +
          geom_violin(aes(x= il6st, y= log2(norm_area), fill = il6st)) +
          geom_point(aes(x= il6st, y= log2(norm_area)), color = 'black') +
          labs(x="il6st level", y="log2(cell area)", title="log2(norm cell area)", subtitle = paste('pvalue =', signif(p$pval, digits = 5))) + 
          scale_fill_manual(values = colors_il6st))
}
dev.off()

```

## FINAL Log2FC PLOTS FOR PAPER
```{r}

# Log2 FC w pval
pdf(file="cellarea_count/plots/log2_pval_norm_1000.pdf")
for(i in unique(area_df$seeding_num)) {
  if(i == '1000'){
    t <- filter_all(area_df, any_vars(.==i))
    t$il6st <- factor(t$il6st, levels = c("Low", "High"))
    p <- filter_all(pvals_df, any_vars(.==i))
    print(ggplot(t) +
            geom_violin(aes(x= il6st, y= log2(norm_area), fill = il6st)) +
            geom_point(aes(x= il6st, y= log2(norm_area)), color = 'black') +
            labs(x="il6st level", y="log2(cell area)", title="log2(norm cell area)", subtitle = paste('pvalue =', signif(p$pval, digits = 5))) + 
            scale_fill_manual(values = colors_il6st))
  }
}
dev.off()


pdf(file="cellarea_count/plots/log2_norm.pdf")
area_df$il6st <- factor(area_df$il6st, levels = c("Low", "High"))
area_df$seeding_num <- factor(area_df$seeding_num, levels = c("500", "1000", "5000"))
ggplot(area_df) +
  geom_violin(aes(x = interaction(il6st, seeding_num), y = log2(norm_area), fill = il6st)) +
  geom_point(aes(x = interaction(il6st, seeding_num), y = log2(norm_area)), color = 'black') +
  labs(x = "il6st level", y = "log2(norm cell area)", title = "log2(norm cell area)", subtitle = pvals_df) + 
  scale_fill_manual(values = colors_il6st)
dev.off()

```